---
ID: "5dcbe600-d399-4e78-a32f-96a95731c588"
Parent: "f063c6da-8c6a-48fa-81c6-454cc5abbe1d"
Template: "f063c6da-8c6a-48fa-81c6-454cc5abbe1d"
Path: "/sitecore/templates/Project/industry-verticals/Custom Templates/Article/Categories/Category Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {3C4EAE73-7E7F-4648-A863-BD250D76CCF8}
    {F063C6DA-8C6A-48FA-81C6-454CC5ABBE1D}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "1293d13f-829d-4686-a3c1-cec3d255b862"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5738b0e4-e1e3-42ff-9e30-5b7023cc76c6"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sanduni.galagoda@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250912T081005Z
