---
ID: "ef9a6e5e-8c5e-40a3-af61-22ddb205e337"
Parent: "b024a2d8-cdde-4338-bd97-fe25248aa3be"
Template: "b024a2d8-cdde-4338-bd97-fe25248aa3be"
Path: "/sitecore/templates/Project/industry-verticals/Components/Page Content/Reviews/Reviews Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {4AEAA1D5-0823-461D-8D2D-94286A5DE0A6}
    {B024A2D8-CDDE-4338-BD97-FE25248AA3BE}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "74779ccb-8bad-4faf-b104-44e4d555984f"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "79301d2f-58c1-4788-84e9-e546231fd7fe"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\isuru.bandara@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251117T095342Z
