---
ID: "4d9f5fa7-589a-4b94-a82d-a6e414930dce"
Parent: "ef999328-1fbd-4c7c-a791-1faff53724bc"
Template: "ef999328-1fbd-4c7c-a791-1faff53724bc"
Path: "/sitecore/templates/Project/industry-verticals/Components/Page Content/Offers/Offers Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {EF999328-1FBD-4C7C-A791-1FAFF53724BC}
    {56DC3DFD-48B8-4DBF-811F-C0CDFAAEA31A}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "266231a6-3148-4186-855d-7ff9a33edba0"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T061559Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "362c0f9b-f676-49df-b098-e7ec5d5f88c5"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\movin.tilakaratne@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250829T074736Z
