---
ID: "f56f0d9f-8cb9-4b66-94aa-541fb600ae7b"
Parent: "0d6bad7e-1341-4ff3-bd72-55791cf1b7af"
Template: "0d6bad7e-1341-4ff3-bd72-55791cf1b7af"
Path: "/sitecore/templates/Project/industry-verticals/Components/Page Content/Deals/Rendering Parameters/Deals Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f96c1ee7-c683-404f-8bc7-22d88f92c7cc"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sanduni.galagoda@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251217T144152Z
