---
ID: "2d977608-7371-4d73-b6d3-47ddd725013f"
Parent: "09dbe61d-b540-470b-b4df-34ba542f66ee"
Template: "98e60957-0783-4a9a-85cc-77dad30e9711"
Path: "/sitecore/content/industry-verticals/nova-medical/Home/Services"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{C0274E9D-2974-4766-A29A-0C4F9FAF8C86}"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 100
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: |
    <image mediaid="{64887F04-BD8E-4095-BC42-5324F51DCF87}" />
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "4f2a8792-6243-4e8d-b4aa-ee05e1ab3396"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:p="p" xmlns:s="s"
      p:p="1">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
        <r
          uid="{30ACA572-3C1B-494E-B907-D96F014B8CDB}"
          s:ds="a08045f1-6d55-4a11-8352-0c5ba319bfaa"
          s:id="{E3CCF1D0-7855-4898-8BDE-77F83C6A487C}"
          s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames=%7B4475AE6C-68CF-4E03-B39D-D80DBC77A4C4%7D&amp;Styles=%7C%7B6B4FBF1C-88C2-42CE-BE88-AB3485078363%7D&amp;RenderingIdentifier&amp;CSSStyles"
          s:ph="headless-main" />
      </d>
    </r>
Languages:
- Language: en
  Fields:
  - ID: "30e85e5d-e00a-4864-b358-7624d511deb4"
    Hint: __Unversioned revision
    Value: "e445c8b5-5412-4a05-8bb5-f40f3be6d07d"
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Services
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{E8C94B8B-CD55-47A8-9F38-3DD712CAC7AC}">
              <p:d />
            </r>
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251117T074821Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Services
    - ID: "4ff91248-33ab-4254-b6f7-2618fd0aebae"
      Hint: Title
      Value: Services
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ranula.gamage@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ranula.gamage@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "796929ce-6749-4760-bbf1-08d761160875"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\movin.tilakaratne@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251202T085334Z
