---
ID: "c2774935-9b30-4e91-a111-d650eea5f6c9"
Parent: "239babbd-8545-49d1-9063-2354e81442f7"
Template: "239babbd-8545-49d1-9063-2354e81442f7"
Path: "/sitecore/templates/Project/industry-verticals/Components/Page Content/Deals/Deals Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {40065854-D68A-4E1C-BDAD-0D61EB39C97C}
    {239BABBD-8545-49D1-9063-2354E81442F7}
    {B044A953-455A-4F8D-B99A-730F9D1818E2}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "ee702a27-afbc-42b3-b4a7-dd29f8772884"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T061559Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fe183346-3eee-401f-a132-e6be6b953bf8"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sanduni.galagoda@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251218T125339Z
