---
ID: "36a6d90f-3cf7-4af2-bb26-8cea55256155"
Parent: "55c6da0f-cd60-4ef3-ae37-5dec60808216"
Template: "55c6da0f-cd60-4ef3-ae37-5dec60808216"
Path: "/sitecore/templates/Project/industry-verticals/Components/Navigation/IconLinkList/IconLinkList/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{4369B92A-53F5-4FE4-BF3B-BAE965133A61}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "1ac3ab8b-2e9d-4a73-a3a6-4c71b4530a57"
- ID: "f7b94d8c-a842-49f8-ab7a-2169d00426b0"
  Hint: __Should Not Organize In Bucket
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20111206T092520Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "51fffd58-fdd2-4876-b3e5-93f51bce3f05"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\jeral.sandeeptha@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251215T170005Z
