---
ID: "b0e0595b-d511-4b69-8309-2acf256e53f2"
Parent: "4d2b49e6-1130-444a-b22c-5c7e25d01b56"
Template: "4d2b49e6-1130-444a-b22c-5c7e25d01b56"
Path: "/sitecore/templates/Project/industry-verticals/Pages/ProductCategoryPage/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {C14B6289-8AC2-439C-9E5B-40DE9F820C3F}
    {F6E44A9E-074A-4865-987E-0C2DC00B7AF5}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "e3c24a6a-548e-423d-86d7-77e9bd60d5ec"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250820T091612Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "eb3ff622-3154-4586-829c-c48c4cf3c35c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\movin.tilakaratne@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251016T153029Z
    - ID: "f77b6eec-9e1b-42aa-af08-48e915b5593c"
      Hint: CategoryName
      Value: $name
