---
ID: "9844a31f-c6c3-47bb-80a2-d72ddc6e91d3"
Parent: "3b22a3fa-18d2-47c7-a467-74c984a65ca4"
Template: "3b22a3fa-18d2-47c7-a467-74c984a65ca4"
Path: "/sitecore/templates/Project/industry-verticals/Page Designs/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {8A5C18A1-2384-406A-A9EA-C16FEBB3253B}
    {1105B8F8-1E00-426B-BF1F-C840742D827B}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "b1407e01-2532-4d49-96d8-538032943004"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250820T091614Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "82697f85-a7d8-4f51-aeae-eb9bfc65b969"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250820T091618Z
