---
ID: "a09c7471-42c5-472c-a2a5-6436ebfb9075"
Parent: "02290180-8aa1-4d4f-b5c5-f97d5a995419"
Template: "02290180-8aa1-4d4f-b5c5-f97d5a995419"
Path: "/sitecore/templates/Project/industry-verticals/Components/Destinations/Selected Destinations/Rendering Parameters/Selected Destinations Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e38fa181-8a33-4ca9-9d0e-21226015288a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sanduni.galagoda@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251222T114553Z
