---
ID: "1e575482-7cb3-490c-8f85-12bf5acc3fe6"
Parent: "78264062-4078-48ba-beb8-3bf32a08f91a"
Template: "78264062-4078-48ba-beb8-3bf32a08f91a"
Path: "/sitecore/templates/Project/industry-verticals/Components/Global Elements/Footer/Footer Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {7E3A2360-40FA-456D-8061-307338DD39E0}
    {78264062-4078-48BA-BEB8-3BF32A08F91A}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "bf593331-6fb0-4293-badc-d0e15367dd3d"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fe5de621-dd95-4b94-bee6-bce6a681a6fd"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\jeral.sandeeptha@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250827T081702Z
