---
ID: "b13825df-cdb7-40bb-a229-554941b13913"
Parent: "2646ac82-f2c4-4d7c-81a2-f5f1021a004a"
Template: "c14bf746-030f-4e59-8594-395f6d299e61"
Path: "/sitecore/content/industry-verticals/skywings/Settings/Shared Sites Settings"
BranchID: "55330bb7-6095-414a-b29b-0042ce8d9331"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{4CAE3F14-39ED-448F-A48C-F7A985A6EB77}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251210T131545Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "da8e9ecd-59ca-4bd3-9ae0-22fc6a1a1384"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251210T131545Z
