---
ID: "cc754e62-6c20-4a31-baa7-33e695ba864b"
Parent: "56dc3dfd-48b8-4dbf-811f-c0cdfaaea31a"
Template: "56dc3dfd-48b8-4dbf-811f-c0cdfaaea31a"
Path: "/sitecore/templates/Project/industry-verticals/Components/Page Content/Offers/Offers/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{0B2E48D3-E9E8-4CD0-87C1-DB7B36B6CA08}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "9fd5c802-593c-42cc-afb9-079e4c87c84c"
- ID: "f7b94d8c-a842-49f8-ab7a-2169d00426b0"
  Hint: __Should Not Organize In Bucket
  Value: 1
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20111206T092520Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "51f71805-cdb7-441d-9031-c9a3f933bbf5"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250903T112947Z
