---
ID: "b1c0f8e2-4565-4416-848c-c49b0c3c3cd4"
Parent: "f055ed82-a30e-4ec9-9ca7-2e4ea50f4e82"
Template: "f055ed82-a30e-4ec9-9ca7-2e4ea50f4e82"
Path: "/sitecore/templates/Project/industry-verticals/Components/Page Content/Features/Features Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {82AC1F90-61F1-4812-9553-E1A4C81405FE}
    {F055ED82-A30E-4EC9-9CA7-2E4EA50F4E82}
    {AD148487-7AAE-4095-B602-7F9AEEB3F8B6}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "c8aa79cf-fcca-4707-adb1-523d9501aff0"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T061559Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9396536d-0d24-4f54-a022-bc28f58d0677"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251215T142735Z
