---
ID: "c4120c83-6c8b-4b07-baeb-7f970d0a766b"
Parent: "17862168-9427-4b7d-8b4f-9c5988e9e03a"
Template: "c14bf746-030f-4e59-8594-395f6d299e61"
Path: "/sitecore/content/industry-verticals/essential-living/Settings/Shared Sites Settings"
BranchID: "55330bb7-6095-414a-b29b-0042ce8d9331"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{4CAE3F14-39ED-448F-A48C-F7A985A6EB77}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251111T120534Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "77499322-8dd2-457f-90e7-6b4ea18a2d7c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251111T120534Z
