---
ID: "7cd3a2e2-d6ee-47b9-873a-ac48c70f7b0a"
Parent: "8924b855-c98b-4d63-93ee-88c3cda6db72"
Template: "8924b855-c98b-4d63-93ee-88c3cda6db72"
Path: "/sitecore/templates/Project/industry-verticals/Custom Templates/Destination/Weather/Weather Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {38CE758E-1324-4C58-A125-04D73C6EC5C4}
    {8924B855-C98B-4D63-93EE-88C3CDA6DB72}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "1dab0f24-7a82-457a-8759-8254619dfa34"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "779978db-07e4-436d-b1b2-273f98dc4d8b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sanduni.galagoda@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251217T124008Z
