---
ID: "ddd50dc4-de9f-4467-b7ef-0a8c256dc922"
Parent: "31135a36-23c2-469c-ba62-d742af0540f3"
Template: "31135a36-23c2-469c-ba62-d742af0540f3"
Path: "/sitecore/templates/Project/industry-verticals/Components/Page Content/Promo/Promo Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {08213AFB-9CB4-4C1F-A5DA-865B9A095601}
    {31135A36-23C2-469C-BA62-D742AF0540F3}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "e70de27a-95f0-40d3-97d3-26560bab1a68"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d6db14c6-1b81-4e90-9c30-f70fb6f95982"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\isuru.bandara@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250902T130956Z
