---
ID: "eed3b611-4b28-4574-87b2-fb34625e0954"
Parent: "7f9d839d-70c1-4674-8ffb-33e0b0d38ce9"
Template: "7f9d839d-70c1-4674-8ffb-33e0b0d38ce9"
Path: "/sitecore/templates/Project/industry-verticals/Custom Templates/Article/Authors/Author Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {AE7C9FA3-F2CB-4A02-8781-789897E12044}
    {7F9D839D-70C1-4674-8FFB-33E0B0D38CE9}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "fa4b068a-ea08-4d19-8d43-b243644f6c1b"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "10161547-939b-4135-92bf-d27057ddf138"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sanduni.galagoda@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250911T104123Z
