---
ID: "e48aad9c-e042-45ba-9525-163ecbdee2be"
Parent: "aeaa56b3-a92f-417b-84d9-df09df850263"
Template: "aeaa56b3-a92f-417b-84d9-df09df850263"
Path: "/sitecore/templates/Project/industry-verticals/Components/Page Content/Item Finder/Rendering Parameters/Item Finder Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1caec150-3d88-4c25-8555-c151a8e33c7f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\tharuka.bandara@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251219T091626Z
