---
ID: "82431361-d336-4375-aea1-b4ab9e4ffb81"
Parent: "3e8ec670-491e-4063-8e50-5a63b7c79fe6"
Template: "3e8ec670-491e-4063-8e50-5a63b7c79fe6"
Path: "/sitecore/templates/Project/industry-verticals/Components/Utilities/ThemeEditor/Rendering Parameters/ThemeEditor Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2daf88dc-9c1d-4896-9317-3247ac070188"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251201T100223Z
