---
ID: "89dfc9ad-015c-44be-a50b-85638d176381"
Parent: "5ae8cbc2-91af-4339-8046-6dbe0ef23c34"
Template: "5ae8cbc2-91af-4339-8046-6dbe0ef23c34"
Path: "/sitecore/templates/Project/industry-verticals/Redirect/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120111T082300Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4156a7f5-d5df-4c64-b6c8-e0f4e9b7216e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ranula.gamage@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250924T123211Z
