---
ID: "60e14b3e-bb31-481b-8a61-5604352f56d8"
Parent: "9f7eb765-4566-4dd5-b74f-8bba6a27ba17"
Template: "9f7eb765-4566-4dd5-b74f-8bba6a27ba17"
Path: "/sitecore/templates/Project/industry-verticals/Site Settings/__Standard Values"
SharedFields:
- ID: "bd13b584-36a1-4c4e-aa1c-b4689ee2fae8"
  Hint: CustomCSS
  Value: /* Custom CSS */
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "70c50cc5-9857-4f6f-9ffa-f8b1a195a26f"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251117T220355Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\jeffrey.isham@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\jeffrey.isham@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fdb2ae04-9644-4534-8112-defced0c12c1"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\jeffrey.isham@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251117T220449Z
