---
ID: "f702b07b-85ec-4f48-8daa-8b1547db6331"
Parent: "d96c025a-1d48-464b-9a72-327c8cc413bb"
Template: "d96c025a-1d48-464b-9a72-327c8cc413bb"
Path: "/sitecore/templates/Project/industry-verticals/Custom Templates/Products/Product Tags/Product Tag/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251117T112149Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1d69c803-135a-433e-b883-0b125496a498"
    - ID: "9ce1cd5e-556b-491f-87a9-4027294b99f8"
      Hint: Tag
      Value: $name
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251117T112153Z
