---
ID: "290b4e51-73e8-4289-aa68-6216d3ac5584"
Parent: "66634c4b-bb85-48af-a5ab-ec3c790eef1d"
Template: "66634c4b-bb85-48af-a5ab-ec3c790eef1d"
Path: "/sitecore/templates/Project/industry-verticals/Components/Page Content/Offers/Offer Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {66634C4B-BB85-48AF-A5AB-EC3C790EEF1D}
    {0B2E48D3-E9E8-4CD0-87C1-DB7B36B6CA08}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "f1048586-90d9-4549-a3dc-a8ab70500788"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T061559Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d429cbc0-48a0-46b9-a54f-0299a4e129c3"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\movin.tilakaratne@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250828T151848Z
