---
ID: "170c57a3-ec55-4515-aa22-5a366c61790f"
Parent: "d152bca4-9b1b-4316-ab22-3e8c0f9dd45e"
Template: "d152bca4-9b1b-4316-ab22-3e8c0f9dd45e"
Path: "/sitecore/templates/Project/industry-verticals/Components/Destinations/Destination Listing/Rendering Parameters/Destination Listing Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5b93f928-16d3-4206-bf1e-803cf1776f87"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sanduni.galagoda@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251223T104207Z
