---
ID: "312d7c17-815f-4020-8eea-8cf721ee2418"
Parent: "4f00880e-dfce-40df-ac79-aa0b3025540b"
Template: "9f7eb765-4566-4dd5-b74f-8bba6a27ba17"
Path: "/sitecore/content/industry-verticals/nova-medical/Settings/Theme Settings"
SharedFields:
- ID: "bd13b584-36a1-4c4e-aa1c-b4689ee2fae8"
  Hint: CustomCSS
  Value: 
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "ccea0f15-d6c1-4712-90d5-66fc799bf620"
- ID: "f4f80dc4-7985-4bba-a11e-4daebba94481"
  Hint: ThemeDefaults
  Value: |
    --color-background: #ffffff;
    --color-background-secondary: #f4fdfd;
    --color-background-tertiary: #b8eff2;
    --color-foreground: #023859;
    
    --color-background-dark: #011119;
    --color-background-secondary-dark: #047294;
    --color-background-tertiary-dark: #023859;
    --color-foreground-dark: #ffffff;
    --color-foreground-secondary-dark: #b8eff2;
    
    --color-accent: #6cd8c9;
    --color-accent-muted: #a3ddcf;
    
    --color-background-input: #e7f7f4;
    --color-disabled: #dcdcdc;
    --color-disabled-dark: #70a7b8;
    
    --color-border: #e8e8e8;
    
    --font-heading: 'Mulish', sans-serif;
    --font-body: 'Noto Sans', sans-serif;
    
    --radius-base: 0.5rem;
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251117T220631Z
    - ID: "38c79e1a-489b-431d-b04e-aefea3c09438"
      Hint: FontOptions
      Value: |
        [
          {
            "label": "Sans Serif",
            "suffix": ", sans-serif",
            "fonts": [
              {
                "name": "Anton",
                "link": "https://fonts.googleapis.com/css2?family=Anton&display=swap"
              },
              {
                "name": "Bebas Neue",
                "link": "https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap"
              },
              {
                "name": "Inter",
                "link": "https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap"
              },
              {
                "name": "Lato",
                "link": "https://fonts.googleapis.com/css2?family=Lato:wght@100..900&display=swap"
              },
              {
                "name": "Manrope",
                "link": "https://fonts.googleapis.com/css2?family=Manrope:wght@200..800&display=swap"
              },
              {
                "name": "Montserrat",
                "link": "https://fonts.googleapis.com/css2?family=Montserrat:wght@100..900&display=swap"
              },
              {
                "name": "Mulish",
                "link": "https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,200..1000;1,200..1000&display=swap"
              },
              {
                "name": "Noto Sans",
                "link": "https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&display=swap"
              },
              {
                "name": "Nunito",
                "link": "https://fonts.googleapis.com/css2?family=Nunito:wght@200..1000&display=swap"
              },
              {
                "name": "Open Sans",
                "link": "https://fonts.googleapis.com/css2?family=Open+Sans:wght@300..800&display=swap"
              },
              {
                "name": "Oswald",
                "link": "https://fonts.googleapis.com/css2?family=Oswald:wght@200..700&display=swap"
              },
              {
                "name": "Poppins",
                "link": "https://fonts.googleapis.com/css2?family=Poppins:wght@100..900&display=swap"
              },
              {
                "name": "Roboto",
                "link": "https://fonts.googleapis.com/css2?family=Roboto:wght@100..900&display=swap"
              },
              {
                "name": "Rubik",
                "link": "https://fonts.googleapis.com/css2?family=Rubik:wght@300..900&display=swap"
              }
            ]
          },
          {
            "label": "Serif",
            "suffix": ", serif",
            "fonts": [
              {
                "name": "Abril Fatface",
                "link": "https://fonts.googleapis.com/css2?family=Abril+Fatface&display=swap"
              },
              {
                "name": "Cormorant",
                "link": "https://fonts.googleapis.com/css2?family=Cormorant:wght@300..700&display=swap"
              },
              {
                "name": "Libre Baskerville",
                "link": "https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital,wght@0,400..700;1,400..700&display=swap"
              },
              {
                "name": "Lora",
                "link": "https://fonts.googleapis.com/css2?family=Lora:wght@400..700&display=swap"
              },
              {
                "name": "Merriweather",
                "link": "https://fonts.googleapis.com/css2?family=Merriweather:wght@300..900&display=swap"
              },
              {
                "name": "Playfair Display",
                "link": "https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400..900&display=swap"
              },
              {
                "name": "Roboto Serif",
                "link": "https://fonts.googleapis.com/css2?family=Roboto+Serif:wght@100..900&display=swap"
              }
            ]
          },
          {
            "label": "Monospace",
            "suffix": ", monospace",
            "fonts": [
              {
                "name": "Fira Code",
                "link": "https://fonts.googleapis.com/css2?family=Fira+Code:wght@300..700&display=swap"
              },
              {
                "name": "Roboto Mono",
                "link": "https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@100..700&display=swap"
              },
              {
                "name": "Source Code Pro",
                "link": "https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@200..900&display=swap"
              },
              {
                "name": "Space Mono",
                "link": "https://fonts.googleapis.com/css2?family=Space+Mono:wght@400..700&display=swap"
              }
            ]
          },
          {
            "label": "Display",
            "suffix": ", cursive",
            "fonts": [
              {
                "name": "Great Vibes",
                "link": "https://fonts.googleapis.com/css2?family=Great+Vibes&display=swap"
              },
              {
                "name": "Pacifico",
                "link": "https://fonts.googleapis.com/css2?family=Pacifico&display=swap"
              },
              {
                "name": "Satisfy",
                "link": "https://fonts.googleapis.com/css2?family=Satisfy&display=swap"
              }
            ]
          }
        ]
        
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "282d5872-b571-415a-be7c-b43bf11e139a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\INIwVuCCf0fzziGGBdz0UepKJ8K6him7
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251208T140919Z
